src/ontology/fbcv-edit.obo

Neuron tools

---

src/ontology/fbcv-edit.obo

-dependent to -regulated in 3 term names

---

src/ontology/fbcv-edit.obo

added sensor tools

---

src/ontology/fbcv-edit.obo

added proximity labelling tools

---

src/ontology/fbcv-edit.obo

Cell labelling tools

---

src/ontology/fbcv-edit.obo

added small molecule-regulated protein cleavage tag

---

src/ontology/fbcv-edit.obo

Added split recombinase, edit to split reporter enzyme definition
fixes #40

Split recombinase

---

src/ontology/fbcv-edit.obo

added meganuclease, minor edit to nuclease definition

---

src/ontology/fbcv-edit.obo

need to deicide what to do about 'antibody' (and add 'nanobody')
other binding tools from #43 added

Binding tools

---

fbcv-base.json
fbcv-base.obo
fbcv-base.owl
fbcv-flybase.obo
fbcv-full.json
fbcv-full.obo
fbcv-non-classified.json
fbcv-non-classified.obo
fbcv-simple.json
fbcv-simple.obo
fbcv-simple.owl
fbcv.json
fbcv.obo

All problems solved now... phew.

Release 14.08.2019

---

src/ontology/fbcv-edit.obo

added lecture

---

src/ontology/fbcv-edit.obo

common_tool_use subset added to 4 terms

---

src/ontology/fbcv-edit.obo

added light conditional term

---

src/ontology/fbcv-edit.obo

added RMCE donor and target elements

---

src/ontology/fbcv-edit.obo

added docking element term

---

src/ontology/fbcv-edit.obo

added RNA engineering tool and RNA-guided ribonuclease

---

src/ontology/fbcv-edit.obo

Mesh links

---

src/ontology/fbcv-edit.obo

namespace for lecture

---

src/ontology/fbcv-edit.obo

and minor modifications to other degredation tags
fixes #109

light-regulated gene product degradation tag

---

src/ontology/fbcv-edit.obo

Minor edits to fix duplicate definitions
Some other definitions copied in from PATO where none previously
related to #91

Definition edits

---

src/ontology/fbcv-edit.obo

minor edit to progressive qualifier
fixes #111

progressive

---

src/ontology/fbcv-edit.obo

Structural qualifiers

---

src/ontology/fbcv-edit.obo

obsoletion of micropublication

---

src/ontology/fbcv-edit.obo
src/ontology/fbcv-idranges.owl

This PR adds a set of new terms that will be needed to annotate scRNAseq datasets for their inclusion into FlyBase.
It also assigns an ID range to me, since it's my first contribution to FBcv.
related to #138

New terms for annotating scRNAseq datasets

---

src/ontology/fbcv-edit.obo

removal of SGML synonyms

---

src/ontology/fbcv-edit.obo

Add a new biosample attribute to represent samples obtained from larvae or adult flies that were starved before being collected.
close #153

Add biosample attribute 'starvation'.

---

src/ontology/fbcv-edit.obo

Add new `biosample method` terms to represent samples obtained by various means of cell dissociation.
close #155

Add `cell dissociation` and related terms.

---

src/ontology/fbcv-edit.obo

light-regulated nuclear export signal

---

src/ontology/fbcv-edit.obo

minor edits to definitions

---

src/ontology/fbcv-edit.obo

conditional splits

---

src/ontology/fbcv-edit.obo

Conditional split recombinases

---

src/ontology/fbcv-edit.obo

light-regulated nuclear protein localization tag

---

src/ontology/fbcv-edit.obo

adding EFO xrefs

---

src/ontology/fbcv-edit.obo

add 'binary expression system - light-regulated driver'

---

src/ontology/fbcv.Makefile
src/scripts/chado_load_checks.pl

Get the latest version of the chado_load_checks.pl script with the re-activated check for ISBN validity.
closes #63

Update the chado_load_checks script.

---

src/ontology/fbcv-edit.obo
src/ontology/fbcv.Makefile
src/ontology/flybase_additions.obo
src/scripts/FB_typedefs.py

related to https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/1687

Relationships

---

src/ontology/fbcv.Makefile

As in FBbt and DPO, definitions in FBcv are processed by the EQWriter tool to:
* replace “dot definitions” (`"."`) with definitions automatically generated from logical definitions;
* replace patterns of the form `$sub_PFX:1234` (where “PFX:1234” is a reference to a foreign term) with the definition of the referenced foreign term.
This PR replaces the use of the EQWriter tool by a specialised ROBOT plugin.

Replace the old EQWriter tool by a ROBOT plugin.

---

src/ontology/fbcv-edit.obo

Subclasses of 'pathway group'

---

src/ontology/fbcv-edit.obo

add new reporter enzymes

---

src/ontology/fbcv-edit.obo

Edits to degradation tool terms

---

src/ontology/fbcv-edit.obo

This PR adds a new experimental tool “split specific binding tool”.
closes #245

Add 'split specific binding tool'.

---

src/ontology/fbcv-edit.obo

This PR adds “single-cell combinatorial indexing RNA sequencing” (“sci-RNA-sea”) as a new assay attribute to qualify scRNAseq dataset objects.
closes #252

Add "sci-RNA-seq".
